### ISSUE TITLE
Could not find EGL in Mac OSX

### ISSUE THREAD

**Issue by nicklhy** [google-research/football#247] opened 2020-11-16 09:57 UTC
Hi, I tried to install gfootball following the instructions in README.md, but got an error like below
```
-- Found OpenGL: /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/OpenGL.framework
CMake Error at CMakeModules/FindPackageHandleStandardArgs.cmake:110 (MESSAGE):
  Could NOT find EGL (missing: EGL_LIBRARY EGL_INCLUDE_DIR)
Call Stack (most recent call first):
  CMakeModules/FindPackageHandleStandardArgs.cmake:301 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindEGL.cmake:72 (find_package_handle_standard_args)
  CMakeLists.txt:34 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
```
It seems the gfootball_engine needs EGL library and can not find it in my Mac OSX system. Did I miss something about the installation steps ?

**Comment by vi3itor** [comment] 2020-11-16 10:51
Indeed, the latest version of GRF requires EGL to support off-screen rendering. But it's not the case for MacOS, and as far as I know, EGL is not supported on Mac OS. I'll check if it is possible to add a quick fix and will send a PR.

**Comment by yagelmeister** [comment] 2021-01-06 11:27
Hi there, same problem for me. I get the following error, which also seems to be caused by not having EGL on Mac OS.

`-- Found OpenGL: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework
    CMake Error at CMakeModules/FindPackageHandleStandardArgs.cmake:110 (MESSAGE):
      Could NOT find EGL (missing: EGL_LIBRARY EGL_INCLUDE_DIR)
    Call Stack (most recent call first):
      CMakeModules/FindPackageHandleStandardArgs.cmake:301 (_FPHSA_FAILURE_MESSAGE)
      CMakeModules/FindEGL.cmake:72 (find_package_handle_standard_args)
      CMakeLists.txt:34 (FIND_PACKAGE)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/hw/dyq__c391dsg1b9zg4j1dqyw0000gn/T/pip-req-build-b49lq4k2/third_party/gfootball_engine/CMakeFiles/CMakeOutput.log".
    See also "/private/var/folders/hw/dyq__c391dsg1b9zg4j1dqyw0000gn/T/pip-req-build-b49lq4k2/third_party/gfootball_engine/CMakeFiles/CMakeError.log".
    gfootball/build_game_engine.sh: line 27: pushd: third_party/gfootball_engine: No such file or directory
    error: Google Research Football compilation failed
`

Is there a quick fix to this?

**Comment by vi3itor** [comment] 2021-01-07 04:26
Hi! Unfortunately, there is no quick fix at the moment. Basically, it requires to update `opengl_renderer3d.cpp`, `opengl_renderer3d.hpp` and `CMakeLists.txt` with OS-specific `if-else` statements to avoid loading EGL library on macOS. If anyone can do it, please send the PR to the Google team. Otherwise, I can give it a try in a week, on January 15. 
For those who want to run the game now, use the previous version (2.7).

**Comment by yagelmeister** [comment] 2021-01-08 16:10
Thank you for replying so quickly. I do not understand what you mean with version 2.7, as the current version of gfootball is 2.0.4? Or are you implying that Python 2.7 should be used?
I can also wait until those files are update.

**Comment by vi3itor** [comment] 2021-01-09 07:56
No problem! 
See the [`CHANGELOG`](https://github.com/google-research/football/blob/master/CHANGELOG) for the current version, it is 2.8 from October 27. You can check out [previous commits](https://github.com/google-research/football/commits/master) and try running earlier versions of the game.

**Comment by vi3itor** [comment] 2021-04-27 09:20
@nicklhy @yagelmeister You can check out PR (#269), everything should work now.

**Comment by qstanczyk** [comment] 2021-09-22 12:42
PR #277 is not merged, Windows support added to the environment. Thanks @vi3itor for your great contribution. Closing this issue.

**Closed by qstanczyk** 2021-09-22 12:42 UTC
