### ISSUE TITLE
Unable to install via pip in editable mode

### ISSUE THREAD

**Issue by avikj** [google-research/football#238] opened 2020-10-25 02:08 UTC
I'm trying to install the gfootball library in a way that I can edit the library code without re-installing the module each time to reflect changes.

To do so, I'm running `pip install -e .`

This fails with error code 1, even though it installs fine if I don't include the -e flag. Any ideas why this might happen or how I can deal with it?

Command output for reference (here, I installed it normally successfully, uninstalled, and tried to install with the -e flag and failed):
```
(gfb-env) avikj@Aviks-MBP-2 football % pip install .   
Processing /Users/avikj/fa20/cs285/football/football
Requirement already satisfied: pygame==1.9.6 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from gfootball==2.7) (1.9.6)
Requirement already satisfied: opencv-python in /Users/avikj/Library/Python/3.7/lib/python/site-packages (from gfootball==2.7) (4.1.2.30)
Requirement already satisfied: scipy in /Users/avikj/Library/Python/3.7/lib/python/site-packages (from gfootball==2.7) (1.4.1)
Requirement already satisfied: gym>=0.11.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from gfootball==2.7) (0.14.0)
Requirement already satisfied: absl-py in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from gfootball==2.7) (0.10.0)
Requirement already satisfied: wheel in /Users/avikj/Library/Python/3.7/lib/python/site-packages (from gfootball==2.7) (0.34.2)
Requirement already satisfied: numpy>=1.14.5 in /Users/avikj/Library/Python/3.7/lib/python/site-packages (from opencv-python->gfootball==2.7) (1.18.4)
Requirement already satisfied: six in /Users/avikj/Library/Python/3.7/lib/python/site-packages (from gym>=0.11.0->gfootball==2.7) (1.14.0)
Requirement already satisfied: cloudpickle~=1.2.0 in /Users/avikj/Library/Python/3.7/lib/python/site-packages (from gym>=0.11.0->gfootball==2.7) (1.2.2)
Requirement already satisfied: pyglet<=1.3.2,>=1.2.0 in /Users/avikj/Library/Python/3.7/lib/python/site-packages (from gym>=0.11.0->gfootball==2.7) (1.3.2)
Requirement already satisfied: future in /Users/avikj/Library/Python/3.7/lib/python/site-packages (from pyglet<=1.3.2,>=1.2.0->gym>=0.11.0->gfootball==2.7) (0.18.2)
Building wheels for collected packages: gfootball
  Building wheel for gfootball (setup.py) ... done
  Created wheel for gfootball: filename=gfootball-2.7-cp37-cp37m-macosx_10_15_x86_64.whl size=10201881 sha256=bf196e98ebd4d2773d9bce3ea00ed54ad5f2be2c7fb988232acd3927ca66875f
  Stored in directory: /private/var/folders/fl/c4kssfz95xng6zc2p3rfvnx00000gn/T/pip-ephem-wheel-cache-15bjp7w7/wheels/6f/80/c0/520566db6c487f3c03a0015912ec14b7e285c3e42e960f7e93
Successfully built gfootball
Installing collected packages: gfootball
Successfully installed gfootball-2.7
WARNING: You are using pip version 20.2.1; however, version 20.2.4 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -m pip install --upgrade pip' command.


(gfb-env) avikj@Aviks-MBP-2 football % pip uninstall gfootball
Found existing installation: gfootball 2.7
Uninstalling gfootball-2.7:
  Would remove:
    /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/brainball_cpp_engine.cpython-37m-darwin.so
    /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gfootball-2.7.dist-info/*
    /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gfootball/*
    /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gfootball_engine/*
Proceed (y/n)? y
  Successfully uninstalled gfootball-2.7


(gfb-env) avikj@Aviks-MBP-2 football % pip install -e .
Obtaining file:///Users/avikj/fa20/cs285/football/football
Requirement already satisfied: pygame==1.9.6 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from gfootball==2.7) (1.9.6)
Requirement already satisfied: opencv-python in /Users/avikj/Library/Python/3.7/lib/python/site-packages (from gfootball==2.7) (4.1.2.30)
Requirement already satisfied: scipy in /Users/avikj/Library/Python/3.7/lib/python/site-packages (from gfootball==2.7) (1.4.1)
Requirement already satisfied: gym>=0.11.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from gfootball==2.7) (0.14.0)
Requirement already satisfied: absl-py in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from gfootball==2.7) (0.10.0)
Requirement already satisfied: wheel in /Users/avikj/Library/Python/3.7/lib/python/site-packages (from gfootball==2.7) (0.34.2)
Requirement already satisfied: numpy>=1.14.5 in /Users/avikj/Library/Python/3.7/lib/python/site-packages (from opencv-python->gfootball==2.7) (1.18.4)
Requirement already satisfied: cloudpickle~=1.2.0 in /Users/avikj/Library/Python/3.7/lib/python/site-packages (from gym>=0.11.0->gfootball==2.7) (1.2.2)
Requirement already satisfied: pyglet<=1.3.2,>=1.2.0 in /Users/avikj/Library/Python/3.7/lib/python/site-packages (from gym>=0.11.0->gfootball==2.7) (1.3.2)
Requirement already satisfied: six in /Users/avikj/Library/Python/3.7/lib/python/site-packages (from gym>=0.11.0->gfootball==2.7) (1.14.0)
Requirement already satisfied: future in /Users/avikj/Library/Python/3.7/lib/python/site-packages (from pyglet<=1.3.2,>=1.2.0->gym>=0.11.0->gfootball==2.7) (0.18.2)
Installing collected packages: gfootball
  Running setup.py develop for gfootball
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/avikj/fa20/cs285/football/football/setup.py'"'"'; __file__='"'"'/Users/avikj/fa20/cs285/football/football/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/avikj/fa20/cs285/football/football/
    Complete output (15 lines):
    running develop
    running egg_info
    writing gfootball.egg-info/PKG-INFO
    writing dependency_links to gfootball.egg-info/dependency_links.txt
    writing requirements to gfootball.egg-info/requires.txt
    writing top-level names to gfootball.egg-info/top_level.txt
    reading manifest file 'gfootball.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'gfootball.egg-info/SOURCES.txt'
    running build_ext
    cp: build/lib.macosx-10.9-x86_64-3.7/gfootball_engine: No such file or directory
    cp: third_party/fonts: unable to copy extended attributes to build/lib.macosx-10.9-x86_64-3.7/gfootball_engine: No such file or directory
    cp: build/lib.macosx-10.9-x86_64-3.7/gfootball_engine/LICENSE: No such file or directory
    cp: build/lib.macosx-10.9-x86_64-3.7/gfootball_engine/AlegreyaSansSC-ExtraBold.ttf: No such file or directory
    error: Google Research Football: Could not copy fonts to build/lib.macosx-10.9-x86_64-3.7/gfootball_engine.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/avikj/fa20/cs285/football/football/setup.py'"'"'; __file__='"'"'/Users/avikj/fa20/cs285/football/football/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
WARNING: You are using pip version 20.2.1; however, version 20.2.4 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -m pip install --upgrade pip' command.
(gfb-env) avikj@Aviks-MBP-2 football % 
```

**Comment by eliyara** [comment] 2020-11-08 20:43
any update on this issue? I am facing the same error! Tried both linux and mac with different versions of Python.

**Comment by ReinholdM** [comment] 2020-11-18 02:45
any update on this issue?

**Comment by ReinholdM** [comment] 2020-11-18 02:58
@eliyara @avikj Hi! I just fixed this issue by executing the following code
`sudo apt-get install git cmake build-essential libgl1-mesa-dev libsdl2-dev \
libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev libopenal-dev libboost-all-dev \
libdirectfb-dev libst-dev mesa-utils xvfb x11vnc python3-pip`.  
Then `pip install -r requirements.txt` is ok.

**Comment by vi3itor** [comment] 2020-11-18 05:32
@ReinholdM The issue is about installing via `pip` in editable mode (with `-e` argument, see the first comment for details).

**Comment by vi3itor** [comment] 2021-06-21 10:56
Hi @avikj and @eliyara, can you please test [my PR](https://github.com/google-research/football/pull/277) which should also allow development install on any platform?

**Comment by qstanczyk** [comment] 2021-09-22 12:42
PR #277 is not merged, Windows support added to the environment. Thanks @vi3itor for your great contribution. Closing this issue.

**Closed by qstanczyk** 2021-09-22 12:42 UTC
