### ISSUE TITLE
Failed building wheel

### ISSUE THREAD

**Issue by fali007** [google-research/football#128] opened 2020-03-24 07:22 UTC
![Screenshot 2020-03-24 at 12 51 52 PM](https://user-images.githubusercontent.com/28902818/77398847-3e0dbe00-6dce-11ea-9237-5507e286bab8.png)

**Comment by qstanczyk** [comment] 2020-04-01 07:23
Can you run this command with verbose mode so more information is provided?

**Comment by AndreiIonascu** [comment] 2020-04-14 14:44
I have the exactly the same issue on OS X Catalina. I attached the output of the command with verbose [output.txt](https://github.com/google-research/football/files/4475938/output.txt).

**Comment by vi3itor** [comment] 2020-04-15 06:49
@AndreiIonascu @fali007 
I think I figured out the cause of the problem. Brew is slowly moving to Python 3.8 and updates its formulas. Starting from recently boost-python3 depends on python@3.8, but we're using Python 3.7. 
The easiest way is to uninstall boost-python3: 
`brew uninstall boost-python3` 
and install it from the last formula that supported Python 3.7: 
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/527d96f84d4632d30b281ef5b26717e0a75edcb4/Formula/boost-python3.rb`
Please try this solution, and if it works, I'll prepare a PR to update README.

**Comment by aries-M** [comment] 2020-04-15 14:16
It works! I solved the same problem by downgrading boost-python3 on Mac OS.

**Comment by AndreiIonascu** [comment] 2020-04-16 13:32
Yes, now it works! Love you man

**Comment by myidispg** [comment] 2020-05-13 03:49
Any solution for this issue on Ubuntu?

**Comment by vi3itor** [comment] 2020-05-13 03:56
@myidispg It is a general error message. You should log your pip output and present it here. Run:
`pip install . --log log.txt`
and attach `log.txt` file (e.g. by dragging & dropping it).

**Comment by myidispg** [comment] 2020-05-13 04:05
Sure, here is the log:
[log.txt](https://github.com/google-research/football/files/4619738/log.txt)

**Comment by vi3itor** [comment] 2020-05-13 04:23
It looks like you're missing sdl2. 
Did you run: 
`sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev`? 
If yes, you can also try reinstalling them: 
`sudo apt-get install --reinstall libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev`
And run pip again: 
`pip install . --log log.txt`

**Comment by myidispg** [comment] 2020-05-13 04:29
Yes, I followed the instructions in README.md for Linux:
```
sudo apt-get install git cmake build-essential libgl1-mesa-dev libsdl2-dev \
libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev libboost-all-dev \
libdirectfb-dev libst-dev mesa-utils xvfb x11vnc libsdl-sge-dev python3-pip
```
Anyways, I reinstalled them and got the same error again. Here is the log:
[log.txt](https://github.com/google-research/football/files/4619811/log.txt)

**Comment by vi3itor** [comment] 2020-05-13 05:02
I don't know why it is happening on your machine. 
After installing SDL2, you should have a file: 
`/usr/lib/x86_64-linux-gnu/cmake/SDL2/sdl2-config.cmake` 
Try investigating further why you don't have this file or why cmake can not find it.

**Comment by vi3itor** [comment] 2020-05-13 05:03
If you find a solution, share it here so that others can benefit from it too.

**Comment by dave7895** [comment] 2020-06-24 12:15
I had a different but strange error.
[log.txt](https://github.com/google-research/football/files/4825279/log.txt)
I could run football anyways by directly calling `python3 setup.py` first with `build` then with `install` and `python3 -m gfootball.play_game --action_set=full` afterwards. I do not have any idea what could cause this.

**Comment by vi3itor** [comment] 2020-06-25 03:32
@dave7895, the log shows that you've created a virtual environment with Python 3.8. I haven't tested if the current setup (including all the dependencies) works with the latest Python version.

**Comment by dave7895** [comment] 2020-06-28 20:21
I came to realize that a bit later as I tried to install tensorflow 1.15 and there weren't any available versions before 2.2.0-rc3. Then I installed anaconda to avoid the manual painful installing of additional python versions. Afterwards it worked fine. Thanks for the tip.
So I can say that automatic building with pip does not work for gfootball and older tensorflow with python3.8. I cannot say anything about tensorflow, but gfootball worked by compiling from the github repo and directly calling `setup.py`.

**Comment by OshriHalimi** [comment] 2020-07-22 15:55
I tried to setup the project on my MacPro using boost-python3 that is provided in the instructions.
I installed in using brew with the flag --ignore-dependencies.
Without the flag is seeps to depend on python 3.8 (maybe this changed since the README was writtern).
Now I get the following errors, trying to compile:

  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/v4/y4j0xnc968b7297b46fgq5580000gn/T/pip-req-build-e8hc_i7x/setup.py'"'"'; __file__='"'"'/private/var/folders/v4/y4j0xnc968b7297b46fgq5580000gn/T/pip-req-build-e8hc_i7x/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/v4/y4j0xnc968b7297b46fgq5580000gn/T/pip-wheel-zk5qz7zl
       cwd: /private/var/folders/v4/y4j0xnc968b7297b46fgq5580000gn/T/pip-req-build-e8hc_i7x/



and also:

    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/v4/y4j0xnc968b7297b46fgq5580000gn/T/pip-req-build-e8hc_i7x/third_party/gfootball_engine/CMakeFiles/CMakeOutput.log".
    gfootball/build_game_engine.sh: line 27: pushd: third_party/gfootball_engine: No such file or directory
    error: Google Research Football compilation failed
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/v4/y4j0xnc968b7297b46fgq5580000gn/T/pip-req-build-e8hc_i7x/setup.py'"'"'; __file__='"'"'/private/var/folders/v4/y4j0xnc968b7297b46fgq5580000gn/T/pip-req-build-e8hc_i7x/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/v4/y4j0xnc968b7297b46fgq5580000gn/T/pip-record-49a9hv67/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/gfootball Check the logs for full command output.

**Comment by vi3itor** [comment] 2020-07-23 15:10
@OshriHalimi You're right, `brew` finally transitioned to Python 3.8 as a default formula. It means that we can start using the latest versions of python3, boost, boost-python3 as long as all the dependencies support it and the project compiles and runs without errors.
I have just upgraded Python, boost, and boost-python3, and was able to compile and run the game. 

If you've already installed all the required packages with brew, it should be enough to run `brew upgrade boost-python3` and then check `brew info` for each package: 
`brew info python` should give you the following output: 
```bash
python@3.8: stable 3.8.5 (bottled)
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python@3.8/3.8.5 (4,397 files, 67.8MB) *
```
Next `brew info boost` should give:
```bash
boost: stable 1.72.0 (bottled), HEAD
Collection of portable C++ source libraries
https://www.boost.org/
/usr/local/Cellar/boost/1.72.0_3 (14,466 files, 648.3MB) *
``` 
And finally `brew info boost-python3` output should be:
```bash
boost-python3: stable 1.72.0 (bottled), HEAD
C++ library for C++/Python3 interoperability
https://www.boost.org/
/usr/local/Cellar/boost-python3/1.72.0_1 (472 files, 20MB) *
```

After that, I recommend creating a virtual environment: 
```bash
python3 -m venv football-env
source football-env/bin/activate
```
and run `pip3 install gfootball`.
If you have any errors, run `pip3 install gfootball --log log.txt` and attach your log here. 
By the way, I had a problem with installing `pygame`, it gave me `src_c/_pygame.h:216:10: fatal error: 'SDL.h' file not found` error. Which is weird, because `pygame` should support SDL2. 
Anyway, I followed the advice from [deepmind's repo](https://github.com/deepmind/pysc2/issues/20#issuecomment-321967886) and installed an older version of SDL too: 
`brew install sdl sdl_image sdl_mixer sdl_ttf portmidi` which solved the problem for me. 

Please share if it solves your problem and I'll prepare a PR.

**Comment by OshriHalimi** [comment] 2020-07-23 18:00
Dear @vi3itor,
Yes, the problem was solved! 👍 

I had to use your suggestion, and install
`brew install sdl sdl_image sdl_mixer sdl_ttf portmidi`

and then the setup was successful.
Thanks!

**Comment by GoingMyWay** [comment] 2020-08-19 01:13
Dear @vi3itor ,  My concern is now there are still some issues in using TF under Python3.8, but brew updates Python dependencies to 3.8, even we use Python 3.8, current DL framework cannot support that fast. Anyway, if you can provide wheel files without compiling locally for users, maybe it is much easier to install.  I am not an expert in building libraries, please correct me if I am wrong.

**Comment by qstanczyk** [comment] 2020-11-04 10:41
Easiest way to go is through Docker - that way you get required versions of libs.

**Closed by qstanczyk** 2020-11-04 10:41 UTC
