### ISSUE TITLE
Python Core  Dumped

### ISSUE THREAD

**Issue by Falergon** [google-research/football#10] opened 2019-06-12 12:14 UTC
I am trying to run  the commands in python as described in the paper.
env = football_env.create_environment(env_name='11_vs_11_stochastic',render=True)
env.reset()
done = False
while not done:
	action = env.action_space.sample()
	observation, reward, done, info = env.step(action)
But every time I get the same error

python3: /tmp/pip-build-8hrcw4hm/gfootball/third_party/gfootball_engine/src/base/utils.cpp:244: blunted::Vector3 blunted::GetVectorFromString(const string&): Assertion `tokenizedString.size() <= 3' failed.
Aborted (core dumped)

**Comment by cyfra** [comment] 2019-06-12 14:28
Thanks for the bug report - could you also mention how you've installed the environment ? (docker, from pypi ? from source?)

**Comment by qstanczyk** [comment] 2019-06-12 14:52
Also, are you sure you don't have any local changes made to the environment?

**Comment by Falergon** [comment] 2019-06-12 15:36
Yes I did not change anything. I just ran the recommended code from the paper.

import gfootball.env as football_env

env = football_env.create_environment(env_name='11_vs_11_stochastic',render=True)
env.reset()
done = False
while not done:
	action = env.action_space.sample()
	observation, reward, done, info = env.step(action)

I installed using pypi.

**Comment by Falergon** [comment] 2019-06-12 22:33
Update: the Error is caused by the env.reset() command

**Comment by qstanczyk** [comment] 2019-06-13 10:08
We are not able to reproduce this problem. Could you make a code change inside utils.cpp:GetVectorFromString function in order to log the input vecString being passed to this method upon hitting a problem? Would be great to also get a stack trace from there, you can replace assert with
    if (tokenizedString.size()  > 3) {
      Log(e_FatalError...
    }

Thanks a lot.

**Comment by shi-yan** [comment] 2019-06-13 17:30
I saw the same problem on ubuntu 18.04 with nvidia 1080 ti, python 3.6

the core dump doesn't provide meaningful callstack

**Comment by shi-yan** [comment] 2019-06-15 22:27
the issue appears to be related to the following line:
`from baselines.ppo2 import ppo2`

I wasn't sure if baselines was installed, so I tried
`pip3 install baselines`,

then I got 

```
    You appear to be missing MuJoCo.  We expected to find the file here: /home/xxx/.mujoco/mujoco200
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html

```

it appears MujoCo is a dependency, but it is proprietary

**Comment by cyfra** [comment] 2019-06-17 06:07
@shi-yan - you must install the baselines version from the github (rather than pypi). See #1 for details.

**Comment by shi-yan** [comment] 2019-06-20 06:43
@cyfra you were right, after applying the workaround in #1 , things worked. Thank you!

**Comment by kkurach** [comment] 2019-06-20 09:39
Seems the problem was resolved, so closing the issue.

**Closed by kkurach** 2019-06-20 09:39 UTC
