### ISSUE TITLE
TypeError running random agent in academy_empty_goal_close scenario

### ISSUE THREAD

**Issue by jorgeg96** [google-research/football#54] opened 2019-08-04 23:14 UTC
Hi. I was trying to run an example of a random agent being implemented. But I get the following error:
TypeError                                 Traceback (most recent call last)
<ipython-input-4-e90a397526ae> in <module>
      1 for i in range(1, 10):
----> 2     env.reset()
      3     acc_reward = 0
      4 
      5     while True:

~/anaconda3/envs/football/lib/python3.7/site-packages/gym/core.py in reset(self, **kwargs)
    268 class RewardWrapper(Wrapper):
    269     def reset(self, **kwargs):
--> 270         return self.env.reset(**kwargs)
    271 
    272     def step(self, action):

~/anaconda3/envs/football/lib/python3.7/site-packages/gym/core.py in reset(self, **kwargs)
    255 class ObservationWrapper(Wrapper):
    256     def reset(self, **kwargs):
--> 257         observation = self.env.reset(**kwargs)
    258         return self.observation(observation)
    259 

~/anaconda3/envs/football/lib/python3.7/site-packages/gym/core.py in reset(self, **kwargs)
    256     def reset(self, **kwargs):
    257         observation = self.env.reset(**kwargs)
--> 258         return self.observation(observation)
    259 
    260     def step(self, action):

~/anaconda3/envs/football/lib/python3.7/site-packages/gfootball/env/wrappers.py in observation(self, obs)
     78     """
     79     final_obs = []
---> 80     for a in obs['active']:
     81       o = []
     82       o.extend(obs['left_team'].flatten())

TypeError: list indices must be integers or slices, not str

Could you tell me the reason of this error? Thanks!

**Comment by AntonRaichuk** [comment] 2019-08-05 11:27
Thanks for reporting the issue. We've noticed it shortly after the previous code push and already have a fix for it.
It should be released to github later today/tomorrow.

**Comment by jorgeg96** [comment] 2019-08-06 01:57
Thanks! I'll wait for the fix.

**Comment by qstanczyk** [comment] 2019-08-06 08:09
Fix was just pushed in v1.2 release.

**Comment by hyren** [comment] 2019-08-06 17:39
I have just cloned the latest repo and built from scratch, but I am still getting this error msg.
```
Traceback (most recent call last):
  File "football.py", line 17, in <module>
    e.reset()
  File "/home/hongyu/anaconda3/envs/pearl/lib/python3.5/site-packages/gym/core.py", line 327, in reset
    return self.env.reset()
  File "/home/hongyu/anaconda3/envs/pearl/lib/python3.5/site-packages/gym/core.py", line 317, in reset
    observation = self.env.reset(**kwargs)
  File "/home/hongyu/anaconda3/envs/pearl/lib/python3.5/site-packages/gym/core.py", line 318, in reset
    return self.observation(observation)
  File "/home/hongyu/anaconda3/envs/pearl/lib/python3.5/site-packages/gfootball/env/wrappers.py", line 135, in observation
    frame = obs['frame']
TypeError: list indices must be integers or slices, not str
```

My code is listed below:
```
import gfootball.env as football_env
import os
os.environ["MESA_GL_VERSION_OVERRIDE"]='3.2'   
os.environ["MESA_GLSL_VERSION_OVERRIDE"]='150'

e = football_env.create_environment(
	env_name='academy_empty_goal_close', 
	representation='pixels', 
	# rewards='scoring,checkpoints',
	render=True
)

for i in range(10000):
	e.reset()
	done = False
	while not done:
		_, _, done, _ = e.step(e.action_space.sample())
		# e.render()
```
I feel the error is caused by the incompatibility between different representations and render functions.

**Comment by jorgeg96** [comment] 2019-08-06 17:50
Same as hyren. Still getting that error.

**Comment by AntonRaichuk** [comment] 2019-08-07 08:08
Originally reported bug happened for simple115 representation which was fixed with the push.
The bug reported by hyren is for pixels. We have a fix and hopefully will release it today.

**Comment by qstanczyk** [comment] 2019-08-07 10:02
v1.3 release (just pushed) has a fix to this problem.

**Closed by qstanczyk** 2019-08-07 10:02 UTC
